//
//  SourceListRouter.swift
//  Clean_news_app
//
//  Created by daniel on 18/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SourceListRoutingLogic
{
    func routeToNewsList(segue: UIStoryboardSegue?)
}

protocol SourceListDataPassing
{
    var dataStore: SourceListDataStore? { get }
}

class SourceListRouter: NSObject, SourceListRoutingLogic, SourceListDataPassing
{
    weak var viewController: SourceListViewController?
    var dataStore: SourceListDataStore?
    
    //MARK: Routing
    
    func routeToNewsList(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! NewsListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToNews(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "NewsListViewController") as! NewsListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToNews(source: dataStore!, destination: &destinationDS)
            navigateToNews(source: viewController!, destination: destinationVC)
        }
    }
    
    //MARK: Navigation
    
    func navigateToNews(source: SourceListViewController, destination: NewsListViewController)
    {
        source.show(destination, sender: nil)
    }
    
    //MARK: Passing data
    
    func passDataToNews(source: SourceListDataStore, destination: inout NewsListDataStore)
    {
        destination.source = source.selectedSource
    }
}
