//
//  SourceListModels.swift
//  Clean_news_app
//
//  Created by daniel on 18/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SourceList
{
    // MARK: Use cases
    
    enum Sources
    {
        struct Request
        {
        }
        struct Response
        {
            var data: Result<SourceListModel, Error>
        }
        struct ViewModel
        {
            var data: Result<SourceListModel, Error>
        }
    }
}
