//
//  WebViewRouter.swift
//  Clean_news_app
//
//  Created by daniel on 19/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WebViewRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol WebViewDataPassing
{
    var dataStore: WebViewDataStore? { get }
}

class WebViewRouter: NSObject, WebViewRoutingLogic, WebViewDataPassing
{
    weak var viewController: WebViewViewController?
    var dataStore: WebViewDataStore?
    
    
}
