//
//  NewsListPresenter.swift
//  Clean_news_app
//
//  Created by daniel on 18/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListPresentationLogic
{
    func presentNews(response: NewsList.News.Response)
    func presentPageFinished()
}

class NewsListPresenter: NewsListPresentationLogic
{
    weak var viewController: NewsListDisplayLogic?
    
    // MARK: Do something
    
    func presentNews(response: NewsList.News.Response)
    {
        let viewModel = NewsList.News.ViewModel(data: response.data)
        viewController?.displayNewsList(viewModel: viewModel)
    }
    
    func presentPageFinished() {
        viewController?.displayPageFinished()
    }
}
