//
//  NewsListModels.swift
//  Clean_news_app
//
//  Created by daniel on 18/05/20.
//  Copyright (c) 2020 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewsList
{
    // MARK: Use cases
    
    enum News
    {
        struct Request
        {
            var page: Int?
            var query: String?
            
        }
        struct Response
        {
            var data: Result<NewsListModel, Error>
        }
        struct ViewModel
        {
            var data: Result<NewsListModel, Error>
        }
    }
}
